/*
  # Create wedding party table

  1. New Tables
    - `wedding_party`
      - `id` (integer, primary key)
      - `name` (text, required)
      - `role` (text, required - e.g., 'bride', 'groom', 'bridesmaid', 'groomsman', 'best_man', 'maid_of_honor')
      - `image_url` (text, required)
      - `bio` (text, optional)
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on `wedding_party` table
    - Add policy for public read access
    - Add policy for public write access (for admin functionality)
*/

CREATE TABLE IF NOT EXISTS wedding_party (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  role text NOT NULL,
  image_url text NOT NULL,
  bio text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE wedding_party ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Wedding party is viewable by everyone"
  ON wedding_party
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Wedding party is editable by everyone"
  ON wedding_party
  FOR ALL
  TO public
  USING (true);