/*
  # Create wedding_party table

  1. New Tables
    - `wedding_party`
      - `id` (integer, primary key, auto-increment)
      - `name` (text, required) - Name of the wedding party member
      - `role` (text, required) - Role in the wedding (e.g., Best Man, Maid of Honor)
      - `image_url` (text, required) - URL to the member's photo
      - `bio` (text, optional, default empty) - Short biography
      - `created_at` (timestamp, default now())

  2. Security
    - Enable RLS on `wedding_party` table
    - Add policy for public read access
    - Add policies for authenticated users to manage data
*/

CREATE TABLE IF NOT EXISTS wedding_party (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  role text NOT NULL,
  image_url text NOT NULL,
  bio text DEFAULT '' NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE wedding_party ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Wedding party is viewable by everyone"
  ON wedding_party
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Wedding party is editable by everyone"
  ON wedding_party
  FOR ALL
  TO public
  USING (true);